-- Insert customers into the customer table
INSERT INTO `customer` (`username`, `firstName`, `lastName`, `phone`, `address`, `password`, `status`, `created_at`, `updated_at`) VALUES
('AMAR GOLUI', 'AMAR', 'GOLUI', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SAKTI NATH KHA', 'SAKTI NATH', 'KHA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('AMAR SAHA', 'AMAR', 'SAHA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SAMANTA MURGI', 'SAMANTA', 'MURGI', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('AMIT GHOSE', 'AMIT', 'GHOSE', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SANDIP KHARA', 'SANDIP', 'KHARA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('ANANDA NANDI', 'ANANDA', 'NANDI', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SANJAY DEY', 'SANJAY', 'DEY', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('ASHIM PATRA', 'ASHIM', 'PATRA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SANTANU JANA', 'SANTANU', 'JANA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('ASHOKE MOLLIK', 'ASHOKE', 'MOLLIK', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SANTU POLLEY', 'SANTU', 'POLLEY', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('ASHOKE POLLEY', 'ASHOKE', 'POLLEY', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SHIB SHANKAR SHAW', 'SHIB SHANKAR', 'SHAW', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('BABLU SAMANTA', 'BABLU', 'SAMANTA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SHITAL SHAW', 'SHITAL', 'SHAW', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('BAPPA MONDAL', 'BAPPA', 'MONDAL', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SOURAV SADHUKHA', 'SOURAV', 'SADHUKHA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('BINOD SHAW', 'BINOD', 'SHAW', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SRIKANTA SINGH', 'SRIKANTA', 'SINGH', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('BIPIN DHARA', 'BIPIN', 'DHARA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SUBHRA POLLEY', 'SUBHRA', 'POLLEY', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('BISWAJIT SAHA', 'BISWAJIT', 'SAHA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SUKUMAR SADHUKA', 'SUKUMAR', 'SADHUKA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('DEBASISH KARAR', 'DEBASISH', 'KARAR', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SURESH SHAW 1', 'SURESH', 'SHAW', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('DILIP SHAW', 'DILIP', 'SHAW', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('SWAPAN MAJI', 'SWAPAN', 'MAJI', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('HALU DA', 'HALU', 'DA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('TAPAN PATRA', 'TAPAN', 'PATRA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('JHORO DA', 'JHORO', 'DA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('TULU SOMU', 'TULU', 'SOMU', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('KARTIK DAS', 'KARTIK', 'DAS', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('UTTAM SHEET', 'UTTAM', 'SHEET', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('KHOKON KUNDU', 'KHOKON', 'KUNDU', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('MADAN MOHAN GHOSH', 'MADAN MOHAN', 'GHOSH', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('NANDI BROTHERS', 'NANDI', 'BROTHERS', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('NAYAN DUTTA', 'NAYAN', 'DUTTA', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('NIMAI DEYASI', 'NIMAI', 'DEYASI', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('PULOK SIL', 'PULOK', 'SIL', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW()),
('RAMPRASAD SHEET', 'RAMPRASAD', 'SHEET', NULL, NULL, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true', NOW(), NOW());